# Read connection details from Render Environment Variables
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Explicitly set dialect to avoid startup metadata lookup errors
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Automatically manage database schema tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true